language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install
  - npm audit fix


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "shadow000902"
  - git config user.email "shadow000902@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${blogSource_Token}@${blogSource_Git}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog_source
env:
 global:
   - blogSource_Git: github.com/shadow000902/shadow000902.github.io.git
